Multiprocessing
Square596/bucket pull request #9
Opened 2022-12-01 21:58 UTC by Square596

2022-12-09 12:04 UTC, Alvant requested changes
В целом ОК, но вообще нет) Вы отвёрткой забиваете гвозди, а молотком вкручиваете винты. Выбрали не те инструменты для рассматриваемых задач. Вы пробовали запускать? Было ускорение?) Нет, где файлы — там, я верю, ускоряет. Но уж программа с нитями — разве она даёт выигрыш по сравнению с последовательным исполнением в одном потоке?..

2022-12-09 12:04 UTC, Alvant commented on task11_1.py
> +    threads = [Thread(target=factorize, args=(i,)) for i in list_numbers]
А если чисел надо будет миллион разложить, то будет создано миллион нитей?.. Это не "сломает" компьютер?)

2022-12-09 12:04 UTC, Alvant commented on task11_1.py
> +        thread.start()
Вы не ждёте нигде завершения нитей? То есть запускаете их, и программа выходит?.. Кажется, стоило в планировщике дождаться, чтоб все досчитали. Иначе как-то не понятно, когда конец-то? как его дождаться)

2022-12-09 12:04 UTC, Alvant commented on task11_1.py
> +    Ans = []
Почему с большой буквы имя?

2022-12-09 12:04 UTC, Alvant commented on task11_1.py
> +        if watch[current_thread().name] == min(watch.values()):
Мне кажется, стоило хоть какой-нибудь небольшой sleep вставить внутрь цикла? Чтоб не по "куче тысяч" проверок в секунду проходило, а как-то... с бОльшим интервалом)

2022-12-09 12:04 UTC, Alvant commented on task11_1.py
> +            break
Ок. То есть нить не считается завершённой, пока не напечатает ответ... Ответ при этом уже посчитан. Ок...

2022-12-09 12:04 UTC, Alvant commented on task11_1.py
> +from threading import Thread, current_thread
Мимо)

Артём, вы пробовали смотреть, ускоряет программа или нет? Ну, например, подать на вход 10000 чисел — будет быстрее, чем последовательно числа перебирать?

Я потому спрашиваю, что с помощью нитей как бы нельзя по идее ускорить вычисления. Все нити в Питоне считаются на одном ядре. Вычисления проходят на ядре. Таким образом, у вас все деления/умножения и т.д. проходят последовательно (синхронно). Тогда в чём ускорение, если вся программа и завязана на арифметических операциях?)

2022-12-09 12:04 UTC, Alvant commented on task11_1.py
> +    watch[current_thread().name] = time.time()
Но почему вы решили, что... Хм... А, в планировщике нити стартуют последовательно. Типа какая раньше начала, такая раньше и закончит?.. Почему... В общем, меня смущает то, что у вас вывод сделан по тому, какая нить раньше начала (такую и выводим). Но я пока не уверен, что... Ааа, раньше начала — раньше получила число в цикле от планировщика, а числа идут последовательно, как надо. Ок! Да, согласен) Этим задаётся порядок.

2022-12-09 12:04 UTC, Alvant commented on task11_1.py
> +    global watch
Мне кажется, лучше бы было `global` в самом начале тела функции задать (это что-то "не совсем естественное" — пусть стоит отдельно, в начале).

2022-12-09 12:04 UTC, Alvant commented on task11_1.py
> +    while d * d <= number:
Логику по "собственно разложению" (без нитей и всего такого) можно бы было в отдельный метод вынести, по-моему.

2022-12-09 12:04 UTC, Alvant commented on task11_1.py
> +    launch_threads(args.values)
Почему было не передать `watch` как аргумент функции `factorize`?.. Тогда бы не пришлось с этим `global` заморачиваться.

2022-12-09 12:04 UTC, Alvant commented on task11_2.py
> +from multiprocessing import Pool
Тут тоже не в кассу) Здесь вы пытаетесь из пушки по воробьям. Процессы — для вычислений. Потоки — (в Питоне) только для чтения, скачивания, sleep и т.д., для всего, где "нет вычислений".

Да, с помощью процессов *можно* решить эту задачу с кучей файлов. Но это более тяжеловесный и дорогой подход по сравнению с нитями. То есть с нитями можно сделать то же самое, но ещё лучше) Обработать все файлы в рамках одной программы, а не нескольких.

Это чем-то похоже на телеграм-бота: можно бы было (наверно...) реализовать бота через нити (по нити на пользователя). Но это бы было очень дорого по сравнению с asyncio подходом.

2022-12-09 12:04 UTC, Alvant commented on task11_2.py
> +
А зачем эта пустая строчка?) Я бы print отделил пустой строчкой.

2022-12-09 12:04 UTC, Alvant commented on task11_1.py
> +    threads = [Thread(target=factorize, args=(i,)) for i in list_numbers]
Кстати... не знаю, может вы просто были "не в теме", но... Ааа!.. Хм, нет, всё равно не понял)

Короче) для нитей тоже можно бы было пул использовать. Прикольно, что вы руками это сделали. Но можно было проще)

2022-12-09 12:04 UTC, Alvant commented on task11_2.py
> +        while True:
Нет, снова тут не надо бесконечного. Он "по природе" конечный.

2022-12-09 12:04 UTC, Alvant commented on task11_2.py
> +    print(''.join(pool.starmap(search, separate_txt_iterable(args.path, args.string))))
А, на конце каждой строки из файла будет "\n"? Ок.

2022-12-09 12:09 UTC, Alvant commented on task11_2.py
> +                yield path, file, string
Хах, да, прикольно было увидеть генератор не только в дз по генераторам)

2022-12-09 12:10 UTC, Alvant commented on task11_2.py
> +            if os.path.splitext(file)[1] == '.txt':
Или так:
```python
if file.endswith('.txt'):
```

2022-12-09 14:33 UTC, Square596 commented on task11_2.py
> +        while True:
А я вот что-то не особо понимаю) Как иначе можно сделать построчное считывание?? Просто я вот не знаю, например, как обычно это устроено в каких-нибудь приборах или типа того. Но вот к примеру, у меня в программу постоянно подаются данные и их нужно обрабатывать - я думал об этом когда это делал. По-другому вроде только если просто redlines сделать и прочитать вообще весь файл и сплитить ег она строки, но разве это эффективно по памяти? Придется хранить весь файл сразу и по чуть-чуть его обрабатывать. А я хотел вот сделать чтоб построчно обрабатывалось и "выкидывалось".

2022-12-09 14:37 UTC, Square596 commented on task11_2.py
> +from multiprocessing import Pool
А мне казалось чтение - сложная работа. Ну типа вычисления - нужно распознать файл еще и декодировать его, разве нет?) Но как устроена подобная работа с разлиными файлами я не шарю, на прошлых курсах такого не было...

2022-12-10 16:09 UTC, Alvant commented on task11_2.py
> +from multiprocessing import Pool
Работа, может, и сложная, но в ней ядро как бы не используется. Тут дело не в том, "сложная" или "лёгкая". Тут дело в том, "вычисления" или "работа с файлами/скачивание картинки из интернета/создание запроса к базе данных/и всё-всё-всё, что не вычисления".

2022-12-10 16:10 UTC, Alvant commented on task11_2.py
> +from multiprocessing import Pool
> распознать файл еще и декодировать его

Да тут вроде бы и не нужно декодировать... Может, я сам не сильно в этом шарю 😅 Но просто открыть и прочитать текстовый файл — это вроде не очень сложно.

2022-12-10 16:16 UTC, Alvant commented on task11_2.py
> +from multiprocessing import Pool
@Square596 тут, например, подробнее и, возможно, понятнее расписали, что такое CPU и I/O (и не только) bound задачи: https://stackoverflow.com/a/868664/8094251

2022-12-10 16:21 UTC, Alvant commented on task11_2.py
> +        while True:
Ну, на самом деле тут всё предельно просто. Если знать, что Питон такое умеет делать)
```python
for line in file:
    # do something with line
```
https://stackoverflow.com/a/48124263/8094251

2022-12-10 16:26 UTC, Alvant commented on task11_2.py
> +        while True:
Нет, у вас в целом был нормальный способ. Но как бы... ведь есть лучше)

Можно бы было ещё с указателями файловыми играться (https://stackoverflow.com/a/10140327/8094251; https://stackoverflow.com/questions/10140281/how-to-find-out-whether-a-file-is-at-its-eof#comment73232207_10140327) — тоже бы работало)

2022-12-10 16:27 UTC, Alvant commented on task11_2.py
> +        while True:
> По-другому вроде только если просто redlines сделать и прочитать вообще весь файл и сплитить ег она строки, но разве это эффективно по памяти?

Но это вы правильно заметили, да, все строки сразу — это точно не самый лучший вариант.

2022-12-16 19:47 UTC, Alvant approved these changes

2022-12-16 19:47 UTC, Alvant commented on task11_1.py
> -    watch[current_thread().name] = time.time()
Да, в целом оказалось лишним) Ну ладно, самому написать что-то типа "своего pool-а" тоже не бесполезно, по-моему.

2022-12-16 19:47 UTC, Alvant commented on task11_1.py
> +    print('\n'.join(pool.map(factorize, args.values)))
😐 Я бы всё-таки выделил отдельную строчку для запуска как-никак основного метода программы ("пуск"), а принт в конце уже отдельно.

2022-12-16 19:55 UTC, Alvant approved these changes

2022-12-16 19:55 UTC, Alvant commented on task11_2.py
> -from multiprocessing import Pool
У нитей, кстати, тоже есть Пул. Только он (как ни странно) расположен в другой библиотеке.

2022-12-16 19:55 UTC, Alvant commented on task11_2.py
> +        print(output[:-2]) # delete \n at the last line
```python
output.rstrip('\n')
```

2022-12-16 19:55 UTC, Alvant commented on task11_2.py
> +                yield (path, file, string, ) # this format is specifically for Thread
🤔 Ок... (Здесь, кстати, поясняющий коммент в самый раз)

Хотя... а чем это отличается от того, что было раньше?) Раньше ведь тоже тьюпл как бы вылетал? Или нет? Что Питон выплёвывает, если через строчку несколько, но без скобок? `return 1, 2, 3`

2022-12-16 19:55 UTC, Alvant commented on task11_2.py
> +    threads = [Thread(target=search, args=i) for i in separate_txt_iterable(args.path, args.string)]
Имя `i` здесь совсем не в кассу. Это примерно как назвать девочку Константином.

2022-12-16 19:55 UTC, Alvant commented on task11_2.py
> +        print(output[:-2]) # delete \n at the last line
Стойте, а в каком порядке они текст выводят? Нити, они ведь между собой никак не синхронизуются? Ну, вывела первая, потом вторая, потом снова первая, ещё раз первая, потом успела вторая и т.д.? Не совсем ведь ок?) Каша из строчек в разных файлах.

2022-12-16 20:19 UTC, Square596 commented on task11_2.py
> +                yield (path, file, string, ) # this format is specifically for Thread
А я тупанул) Видимо типы данных не доботал... Мне казалось, что (1, 2, 3) и (1, 2, 3, ) - разные tuple. Типа я сделал так, думая, что именно конечный пробел что-то решает... Но щас понимаю, что когда в thread пишут args=(i, ) это только для того, чтобы аргумент в виде tuple подавался. (честно, я не знал и даже не думал, что (1) = 1, и что (1, ) != (1) )

2022-12-16 20:21 UTC, Square596 commented on task11_2.py
> -from multiprocessing import Pool
Да, да я видел, что такой существует, но не изучал зачем он и как работает

2022-12-16 20:22 UTC, Square596 commented on task11_2.py
> -from multiprocessing import Pool
Тем более он же вроде чисто для конкурирования нитей в одном процессе, без распаралелливания, как я понимаю

2022-12-16 20:22 UTC, Square596 commented on task11_2.py
> +        print(output[:-2]) # delete \n at the last line
Справедливо)

2022-12-16 20:23 UTC, Square596 commented on task11_2.py
> +    threads = [Thread(target=search, args=i) for i in separate_txt_iterable(args.path, args.string)]
типа надо было назвать "arguments"?)

2022-12-16 20:25 UTC, Square596 commented on task11_2.py
> +        print(output[:-2]) # delete \n at the last line
так я для этого как раз сделал переменную output в которой по очереди конкатенируются все выводы, и лишь в самом конце (когда вся книга прочитана) принтуется все вместе для конкретной книги 
(да, можно было отправлять результаты в мейн и оттуда производить принт, но я разницы не особо вижу если честно, поэтому сделал так)

2022-12-22 09:21 UTC, Alvant commented on task11_2.py
> -from multiprocessing import Pool
@Square596 да, для нитей в одном процессе. Если нити читают из файлов или ещё что-то I/O делают — то они могут работать параллельно (не используют ядро). Если они все считают — то, да, "конкурируют" (хотя здесь нет "конкуренции" — тут, скорее, просто чередование ожиданий и исполнений).

2022-12-22 09:22 UTC, Alvant commented on task11_2.py
> +        print(output[:-2]) # delete \n at the last line
Ещё бы) И коммент не нужен)

2022-12-22 09:24 UTC, Alvant commented on task11_2.py
> +                yield (path, file, string, ) # this format is specifically for Thread
Хах, ну, хорошо, что разобрались) Да, `(1,)` — "особый случай", тьюпл из одного элемента. С этим надо просто один раз встретиться и иметь в виду. "Особенность языка".

2022-12-22 09:29 UTC, Alvant commented on task11_2.py
> +    threads = [Thread(target=search, args=i) for i in separate_txt_iterable(args.path, args.string)]
Ну, возможно) Было бы лучше в плане смысла, но выглядело бы немного... "помпезно", слишком торжественно-официально для просто переменной цикла. Можно было просто `args`? или, там, `file_args`, `search_args`, что-то такое.

2022-12-22 09:30 UTC, Alvant commented on task11_2.py
> +        print(output[:-2]) # delete \n at the last line
Ок, тут вроде разобрались.

2022-12-22 09:32 UTC, Alvant commented on task11_2.py
> +    threads = [Thread(target=search, args=i) for i in separate_txt_iterable(args.path, args.string)]
Все нормальные люди используют `i` для индекса) Я даже не могу вот сейчас сходу придумать что-то ещё осмысленное, для чего бы `i` стоило использовать. "Актёр одной роли."

2023-02-06 10:33 UTC, merged